### ISSUE TITLE
TSM-based features for EPIC-100

### ISSUE THREAD

**Issue by yxgz** [dibschat/tempAgg#3]
Hello, thanks for your hard work! It really provides great convenience for reimplementation.

Meanwhile, I would like to know if the TSM-based features for EPIC-100 will be available for download as those of Epic-Kitchens do? Thanks a lot.

**Comment by dibschat** [comment]
We did not use TSM features for our experiments. But you can extract them by following the feature extraction procedure in [RU-LSTM repo](https://github.com/fpv-iplab/rulstm#feature-extraction) and instead of using bninception backbone for TSN use the TSM backbone provided by the EPIC-100 [here](https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/master/src/models/tsm.py).
